### ISSUE TITLE
my order it still pending

### ISSUE THREAD

**Issue by elbombero60** [unixcoin-dev/unixcoin#1]
i place a order for 100 coins on 11-30-17 and today 12-1-17 it still in pending mode
the money has been taking but no coins and still pending it has been 24 hours.

**Comment by kabirbasha786** [comment]
i place a order for 100 coins on 11-30-17 and today 30-1-2017 it still in pending mode
the money has been taking but no coins and still pending it has been 24 hours.please check

**Comment by kabirbasha786** [comment]
Hai I am.kabirbasha786 . I place order for 100 coins 30-11-2017 . It still in pending mode . The money has been taking but no coins and still pending . Please check
